### ISSUE TITLE
Use markdown instead of writing pure html?

### ISSUE THREAD

**Issue by paul-marechal** [UPBGE/UPBGE-Web-old-backup#1]
GitHub pages allow for projects to use markdown files instead of directly writing an html website.

https://guides.github.com/features/pages/#setup
https://github.blog/2016-12-09-publishing-with-github-pages-now-as-easy-as-1-2-3/

The advantage is that it would be easier to write.

**Comment by lordloki** [comment]
Currently we are using an external web server to get more transfer capacity. I close this report as it doesn't apply now. But if one day we return to github web publication we will use markdown as it is easier to maintain. Thanks for the feedback.
