### ISSUE TITLE
Not work the link API UPBGE2.5

### ISSUE THREAD

**Issue by fumangy** [UPBGE/UPBGE-Web-old-backup#4]
Not work the link API UPBGE2.5?
https://pythonapi.upbge.org

https://user-images.githubusercontent.com/29063438/123341332-14ea5900-d54e-11eb-8d06-e6822be1dcd7.mov

**Comment by lordloki** [comment]
Thanks for reporting. I have uploaded the old 0.2.5 manual/API to new direction https://upbge.org/manual_api_0.2.5
I also redirected former pythonapi.upbge.org to the new direction.
Closing.
